name: AWizardDidIt
version: 1.1.1
author: mistergone
main: me.mistergone.AWizardDidIt.AWizardDidIt
api-version: 1.14
description: A Wizard Did It!
commands:
  wizardry:
    description: Commands for AWizardDidIt
    usage: /wizardry <options>