name: AWizardDidIt
version: 0.2.1
author: mistergone
main: me.mistergone.AWizardDidIt.AWizardDidIt
api-version: 1.13
description: A Wizard Did It!
commands:
  wizardry:
    description: Commands for AWizardDidIt
    usage: /wizardry <options>