name: AWizardDidIt
version: 1.5.0
author: mistergone
main: me.mistergone.AWizardDidIt.AWizardDidIt
api-version: 1.19
description: A Wizard Did It!
commands:
  wizardry:
    description: Commands for AWizardDidIt
    usage: /wizardry <options>